import type { BuilderDocument, ComponentManifestEntry, BuilderNode } from "@/types/builder";

export const BUILDER_MANIFEST: ComponentManifestEntry[] = [
  {
    key: "layout.section",
    category: "layout",
    label: "palettes.layout.section.title",
    description: "palettes.layout.section.text",
    defaultProps: {
      background: { type: "solid", value: "surface-50" },
    },
    schema: {},
    styleHandles: [
      {
        id: "spacing",
        label: "Spacing",
        group: "spacing",
        controls: [
          { property: "padding", type: "four-sides" },
          { property: "margin", type: "four-sides" },
        ],
      },
      {
        id: "background",
        label: "Background",
        group: "background",
        controls: [{ property: "background", type: "color" }],
      },
      {
        id: "layout",
        label: "Layout",
        group: "layout",
        controls: [
          { property: "maxWidth", type: "input" },
          { property: "margin", type: "four-sides" },
        ],
      },
    ],
    allowedChildren: [
      "layout.row",
      "layout.columns-2",
      "layout.columns-3",
      "layout.columns-4",
      "layout.container",
      "layout.navbar",
      "layout.footer",
      "content.richText",
      "content.button",
      "content.image",
      "content.link",
      "forms.input",
      "forms.select",
      "forms.textarea",
      "forms.checkbox",
      "forms.radio",
      "forms.datetime",
      "media.video",
      "media.slider",
    ],
  },
  {
    key: "layout.container",
    category: "layout",
    label: "palettes.layout.container.title",
    description: "palettes.layout.section.text",
    defaultProps: {},
    schema: {},
    styleHandles: [
      {
        id: "layout",
        label: "Layout",
        group: "layout",
        controls: [
          { property: "width", type: "input" },
          { property: "maxWidth", type: "input" },
          { property: "margin", type: "four-sides" },
        ],
      },
      {
        id: "spacing",
        label: "Spacing",
        group: "spacing",
        controls: [
          { property: "padding", type: "four-sides" },
        ],
      },
    ],
    allowedChildren: [
      "layout.row",
      "layout.column",
      "content.richText",
      "content.button",
      "content.image",
      "content.logo",
      "content.navLink",
      "content.link",
      "content.stat",
      "forms.input",
      "forms.select",
      "forms.textarea",
      "forms.checkbox",
      "forms.radio",
      "forms.datetime",
      "media.video",
      "media.slider",
    ],
  },
  {
    key: "layout.row",
    category: "layout",
    label: "palettes.layout.row.title",
    description: "palettes.layout.row.text",
    defaultProps: {
      direction: "row",
    },
    schema: {},
    styleHandles: [
      {
        id: "layout",
        label: "Layout",
        group: "layout",
        controls: [
          { property: "display", type: "select", options: { flex: "Flex", grid: "Grid" } },
          { property: "flexDirection", type: "select", options: { row: "Row", column: "Column" } },
          { property: "gap", type: "input" },
        ],
      },
      {
        id: "spacing",
        label: "Spacing",
        group: "spacing",
        controls: [{ property: "padding", type: "four-sides" }],
      },
    ],
    allowedChildren: [
      "layout.column",
      "layout.container",
      "layout.navItem",
      "layout.navDropdown",
      "content.richText",
      "content.button",
      "content.image",
      "content.logo",
      "content.navLink",
      "content.link",
      "content.stat",
      "forms.input",
      "forms.select",
      "forms.textarea",
      "forms.checkbox",
      "forms.radio",
      "forms.datetime",
      "media.video",
      "media.slider",
    ],
  },
  {
    key: "layout.column",
    category: "layout",
    label: "palettes.layout.column.title",
    description: "palettes.layout.column.text",
    defaultProps: {},
    schema: {},
    styleHandles: [
      {
        id: "layout",
        label: "Layout",
        group: "layout",
        controls: [
          { property: "display", type: "select", options: { flex: "Flex", block: "Block" } },
          { property: "gap", type: "input" },
        ],
      },
      {
        id: "spacing",
        label: "Spacing",
        group: "spacing",
        controls: [{ property: "padding", type: "four-sides" }],
      },
    ],
    allowedChildren: [
      "layout.container",
      "content.richText",
      "content.button",
      "content.image",
      "content.logo",
      "content.navLink",
      "content.link",
      "content.stat",
      "forms.input",
      "forms.select",
      "forms.textarea",
      "forms.checkbox",
      "forms.radio",
      "forms.datetime",
      "media.video",
      "media.slider",
    ],
  },
  {
    key: "layout.columns-2",
    category: "layout",
    label: "palettes.layout.two_columns.title",
    description: "palettes.layout.two_columns.text",
    defaultProps: {},
    schema: {},
    styleHandles: [
      {
        id: "layout",
        label: "Layout",
        group: "layout",
        controls: [
          { property: "gap", type: "input" },
          { property: "gridTemplateColumns", type: "input" },
        ],
      },
      {
        id: "spacing",
        label: "Spacing",
        group: "spacing",
        controls: [{ property: "padding", type: "four-sides" }],
      },
    ],
    allowedChildren: ["layout.column"],
  },
  {
    key: "layout.columns-3",
    category: "layout",
    label: "palettes.layout.three_columns.title",
    description: "palettes.layout.three_columns.text",
    defaultProps: {},
    schema: {},
    styleHandles: [
      {
        id: "layout",
        label: "Layout",
        group: "layout",
        controls: [
          { property: "gap", type: "input" },
          { property: "gridTemplateColumns", type: "input" },
        ],
      },
      {
        id: "spacing",
        label: "Spacing",
        group: "spacing",
        controls: [{ property: "padding", type: "four-sides" }],
      },
    ],
    allowedChildren: ["layout.column"],
  },
  {
    key: "layout.columns-4",
    category: "layout",
    label: "palettes.layout.four_columns.title",
    description: "palettes.layout.four_columns.text",
    defaultProps: {},
    schema: {},
    styleHandles: [
      {
        id: "layout",
        label: "Layout",
        group: "layout",
        controls: [
          { property: "gap", type: "input" },
          { property: "gridTemplateColumns", type: "input" },
        ],
      },
      {
        id: "spacing",
        label: "Spacing",
        group: "spacing",
        controls: [{ property: "padding", type: "four-sides" }],
      },
    ],
    allowedChildren: ["layout.column"],
  },
  {
    key: "content.richText",
    category: "content",
    label: "palettes.content.text.title",
    description: "palettes.content.text.text",
    defaultProps: {
      text: "palletes.content.text.placeholder",
      tag: "p",
    },
    schema: {},
    styleHandles: [
      {
        id: "typography",
        label: "Typography",
        group: "typography",
        controls: [
          { property: "fontSize", type: "input" },
          { property: "fontWeight", type: "select", options: { normal: "Normal", bold: "Bold", 600: "Semi Bold" } },
          { property: "lineHeight", type: "input" },
          { property: "color", type: "color" },
          { property: "textAlign", type: "select", options: { left: "Left", center: "Center", right: "Right" } },
        ],
      },
      {
        id: "spacing",
        label: "Spacing",
        group: "spacing",
        controls: [{ property: "margin", type: "four-sides" }],
      },
    ],
  },
  {
    key: "content.button",
    category: "content",
    label: "palettes.content.button.title",
    description: "palettes.content.button.text",
    defaultProps: {
      label: "palettes.content.button.placeholder",
      href: "#",
      variant: "primary",
    },
    schema: {},
    styleHandles: [
      {
        id: "spacing",
        label: "Spacing",
        group: "spacing",
        controls: [{ property: "margin", type: "four-sides" }],
      },
      {
        id: "layout",
        label: "Layout",
        group: "layout",
        controls: [{ property: "width", type: "input" }],
      },
    ],
  },
  {
    key: "content.image",
    category: "media",
    label: "palettes.media.image.title",
    description: "palettes.media.image.text",
    defaultProps: {
      assetId: null,
      alt: "",
      objectFit: "cover",
    },
    schema: {},
    styleHandles: [
      {
        id: "layout",
        label: "Layout",
        group: "layout",
        controls: [
          { property: "width", type: "input" },
          { property: "height", type: "input" },
          { property: "borderRadius", type: "input" },
        ],
      },
    ],
  },
  {
    key: "forms.input",
    category: "forms",
    label: "palettes.forms.input.title",
    description: "palettes.forms.input.text",
    defaultProps: {
      name: "email",
      label: "Email",
      placeholder: "you@example.com",
      type: "email",
      required: true,
    },
    schema: {},
    styleHandles: [
      {
        id: "spacing",
        label: "Spacing",
        group: "spacing",
        controls: [{ property: "margin", type: "four-sides" }],
      },
    ],
  },
  {
    key: "forms.textarea",
    category: "forms",
    label: "palettes.forms.textarea.title",
    description: "palettes.forms.textarea.text",
    defaultProps: {
      name: "message",
      label: "Message",
      placeholder: "Tell us more...",
      rows: 4,
    },
    schema: {},
    styleHandles: [
      {
        id: "spacing",
        label: "Spacing",
        group: "spacing",
        controls: [{ property: "margin", type: "four-sides" }],
      },
    ],
  },
  {
    key: "forms.select",
    category: "forms",
    label: "palettes.forms.select.title",
    description: "palettes.forms.select.text",
    defaultProps: {
      name: "plan",
      label: "Select option",
      options: "Option A\nOption B\nOption C",
    },
    schema: {},
    styleHandles: [
      {
        id: "spacing",
        label: "Spacing",
        group: "spacing",
        controls: [{ property: "margin", type: "four-sides" }],
      },
    ],
  },
  {
    key: "forms.checkbox",
    category: "forms",
    label: "palettes.forms.checkbox.title",
    description: "palettes.forms.checkbox.text",
    defaultProps: {
      label: "Accept terms",
      name: "checkbox",
      defaultChecked: false,
    },
    schema: {},
    styleHandles: [
      {
        id: "spacing",
        label: "Spacing",
        group: "spacing",
        controls: [{ property: "margin", type: "four-sides" }],
      },
    ],
  },
  {
    key: "forms.radio",
    category: "forms",
    label: "palettes.forms.radio.title",
    description: "palettes.forms.radio.text",
    defaultProps: {
      label: "Radio option",
      name: "radio-group",
      value: "option",
      defaultChecked: false,
    },
    schema: {},
    styleHandles: [
      {
        id: "spacing",
        label: "Spacing",
        group: "spacing",
        controls: [{ property: "margin", type: "four-sides" }],
      },
    ],
  },
  {
    key: "forms.datetime",
    category: "forms",
    label: "palettes.forms.datetime.title",
    description: "palettes.forms.datetime.text",
    defaultProps: {
      label: "Date & time",
      name: "datetime",
      defaultValue: "",
    },
    schema: {},
    styleHandles: [
      {
        id: "spacing",
        label: "Spacing",
        group: "spacing",
        controls: [{ property: "margin", type: "four-sides" }],
      },
    ],
  },
  {
    key: "layout.navbar",
    category: "layout",
    label: "palettes.layout.navbar.title",
    description: "palettes.layout.navbar.text",
    defaultProps: {},
    schema: {},
    styleHandles: [
      {
        id: "layout",
        label: "Layout",
        group: "layout",
        controls: [
          { property: "gap", type: "input" },
          { property: "padding", type: "four-sides" },
        ],
      },
    ],
    allowedChildren: ["content.logo", "layout.navMenu", "content.button", "content.link"],
  },
  {
    key: "layout.navMenu",
    category: "layout",
    label: "palettes.layout.nav_menu.title",
    description: "palettes.layout.nav_menu.text",
    defaultProps: {},
    schema: {},
    styleHandles: [
      {
        id: "layout",
        label: "Layout",
        group: "layout",
        controls: [
          { property: "gap", type: "input" },
          { property: "justifyContent", type: "select", options: { "flex-start": "Start", center: "Center", "flex-end": "End", "space-between": "Between" } },
        ],
      },
    ],
    allowedChildren: ["layout.navItem"],
  },
  {
    key: "layout.navItem",
    category: "layout",
    label: "palettes.layout.nav_item.title",
    description: "palettes.layout.nav_item.text",
    defaultProps: {},
    schema: {},
    styleHandles: [
      {
        id: "layout",
        label: "Layout",
        group: "layout",
        controls: [
          { property: "gap", type: "input" },
        ],
      },
    ],
    allowedChildren: ["content.navLink", "content.link", "layout.navDropdown"],
  },
  {
    key: "layout.navDropdown",
    category: "layout",
    label: "palettes.layout.dropdown.title",
    description: "palettes.layout.dropdown.text",
    defaultProps: {},
    schema: {},
    styleHandles: [
      {
        id: "layout",
        label: "Layout",
        group: "layout",
        controls: [
          { property: "gap", type: "input" },
        ],
      },
      {
        id: "spacing",
        label: "Spacing",
        group: "spacing",
        controls: [{ property: "padding", type: "four-sides" }],
      },
    ],
    allowedChildren: ["content.navLink", "content.link"],
  },
  {
    key: "layout.footer",
    category: "layout",
    label: "palettes.layout.footer.title",
    description: "palettes.layout.footer.text",
    defaultProps: {},
    schema: {},
    styleHandles: [
      {
        id: "layout",
        label: "Layout",
        group: "layout",
        controls: [
          { property: "gap", type: "input" },
          { property: "padding", type: "four-sides" },
        ],
      },
    ],
    allowedChildren: [
      "layout.row",
      "content.richText",
      "content.button",
      "content.image",
      "content.logo",
      "content.link",
      "forms.input",
      "forms.select",
      "forms.textarea",
      "forms.checkbox",
      "forms.radio",
      "forms.datetime",
    ],
  },
  {
    key: "content.logo",
    category: "content",
    label: "palettes.content.logo.title",
    description: "palettes.content.logo.text",
    defaultProps: {
      text: "BakeMentor",
      href: "/",
      url: "",
    },
    schema: {},
    styleHandles: [
      {
        id: "spacing",
        label: "Spacing",
        group: "spacing",
        controls: [{ property: "margin", type: "four-sides" }],
      },
    ],
  },
  {
    key: "content.navLink",
    category: "content",
    label: "palettes.content.nav_link.title",
    description: "palettes.content.nav_link.text",
    defaultProps: {
      label: "Menu",
      href: "#",
    },
    schema: {},
    styleHandles: [
      {
        id: "typography",
        label: "Typography",
        group: "typography",
        controls: [
          { property: "fontSize", type: "input" },
          { property: "fontWeight", type: "select", options: { normal: "Normal", 500: "Medium", 600: "Semibold" } },
        ],
      },
    ],
  },
  {
    key: "content.link",
    category: "content",
    label: "palettes.content.text_link.title",
    description: "palettes.content.text_link.text",
    defaultProps: {
      label: "New link",
      href: "https://example.com",
      target: "_self",
    },
    schema: {},
    styleHandles: [
      {
        id: "typography",
        label: "Typography",
        group: "typography",
        controls: [
          { property: "fontSize", type: "input" },
          { property: "fontWeight", type: "select", options: { normal: "Normal", 500: "Medium", 600: "Semibold", 700: "Bold" } },
          { property: "textAlign", type: "select", options: { left: "Left", center: "Center", right: "Right" } },
          { property: "color", type: "input" },
        ],
      },
    ],
  },
  {
    key: "content.stat",
    category: "content",
    label: "palettes.content.statistic.title",
    description: "palettes.content.statistic.text",
    defaultProps: {
      value: "120%",
      label: "Growth rate",
      description: "Increase in conversions",
    },
    schema: {},
    styleHandles: [
      {
        id: "typography",
        label: "Typography",
        group: "typography",
        controls: [
          { property: "fontSize", type: "input" },
          { property: "lineHeight", type: "input" },
        ],
      },
    ],
  },
  {
    key: "media.video",
    category: "media",
    label: "palettes.media.video.title",
    description: "palettes.media.video.text",
    defaultProps: {
      source: "",
      poster: "",
      title: "Product walkthrough",
    },
    schema: {},
    styleHandles: [
      {
        id: "layout",
        label: "Layout",
        group: "layout",
        controls: [
          { property: "width", type: "input" },
          { property: "height", type: "input" },
          { property: "borderRadius", type: "input" },
        ],
      },
    ],
  },
  {
    key: "media.slider",
    category: "media",
    label: "palettes.media.carousel.title",
    description: "palettes.media.carousel.text",
    defaultProps: {
      autoplay: "5000",
    },
    schema: {},
    styleHandles: [
      {
        id: "layout",
        label: "Layout",
        group: "layout",
        controls: [
          { property: "width", type: "input" },
          { property: "height", type: "input" },
          { property: "borderRadius", type: "input" },
        ],
      },
    ],
    allowedChildren: ["content.image"],
  },
];

const initialNodes: Record<string, BuilderNode> = {
  root: {
    id: "root",
    type: "layout",
    component: "layout.section",
    props: {},
    children: [],
    styles: {
      base: {
        backgroundColor: "#ffffff",
        minHeight: "100%",
        width: "100%",
      },
    },
  },
};

export const SAMPLE_DOCUMENT: BuilderDocument = {
  tree: {
    version: "2025-10-01",
    root: "root",
    nodes: initialNodes,
  },
  manifest: BUILDER_MANIFEST,
  assets: [],
  lastSavedAt: new Date().toISOString(),
};
