# Generated by Django 5.2.6 on 2025-10-01 12:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('hero', 'Hero'), ('content', 'Content'), ('media', 'Media'), ('forms', 'Forms'), ('layout', 'Layout'), ('cta', 'Call to action')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('schema', models.JSONField(default=dict)),
                ('props_schema', models.JSONField(blank=True, default=dict)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='component_previews/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('component_tree', models.JSONField(default=dict)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='template_thumbnails/')),
                ('is_public', models.BooleanField(default=False)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
